name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install newman
      run: |
        npm install -g newman

    - name: Run Postman tests
      run: |
        newman run Google.postman_collection.json.json -e ProdUrl.postman_environment.json
